// SPDX-License-Identifier: Apache-2.0 WITH Swift-exception
// Copyright (c) 2026 Xudong Xu

import Foundation

public struct PublicAPIFacadeReport: Codable, Equatable, Sendable {
  public var capabilityCount: Int
  public var operationCount: Int
  public var outputPath: String

  public init(capabilityCount: Int, operationCount: Int, outputPath: String) {
    self.capabilityCount = capabilityCount
    self.operationCount = operationCount
    self.outputPath = outputPath
  }
}

public struct PublicAPIFacadeEmitter: Sendable {
  public init() {}

  public func writeFacade(
    capabilitiesURL: URL,
    selectedOpenAPIURL: URL,
    outputURL: URL
  ) throws -> PublicAPIFacadeReport {
    let source = try facadeSource(
      capabilitiesURL: capabilitiesURL,
      selectedOpenAPIURL: selectedOpenAPIURL
    )
    try FileManager.default.createDirectory(
      at: outputURL.deletingLastPathComponent(),
      withIntermediateDirectories: true
    )
    try source.data(using: .utf8)?.write(to: outputURL, options: .atomic)

    let manifest = try OpenAPICapabilityManifest.load(from: capabilitiesURL)
    let operationCount = try manifest.operationIDs().count
    return PublicAPIFacadeReport(
      capabilityCount: manifest.capabilities.count,
      operationCount: operationCount,
      outputPath: outputURL.path
    )
  }

  public func facadeSource(
    capabilitiesURL: URL,
    selectedOpenAPIURL: URL
  ) throws -> String {
    let manifest = try OpenAPICapabilityManifest.load(from: capabilitiesURL)
    let operationShapes = try loadOperationShapes(from: selectedOpenAPIURL)
    let operationIDs = try manifest.operationIDs()
    var missingOperations: [String] = []

    for operationID in operationIDs where operationShapes[operationID] == nil {
      missingOperations.append(operationID)
    }

    if !missingOperations.isEmpty {
      throw GeneratorCommandError.validationFailed(
        "facade operations not found in selected OpenAPI input: \(missingOperations.joined(separator: ", "))"
      )
    }

    var lines: [String] = [
      "// Generated by AppStoreConnectPublicAPIGen, do not modify.",
      "",
      "public struct AppStoreConnectPublicClient: Sendable {",
      "    public let openAPI: any APIProtocol",
      "",
      "    public init(openAPI: any APIProtocol) {",
      "        self.openAPI = openAPI",
      "    }",
      "",
      "    public init(client: Client) {",
      "        self.openAPI = client",
      "    }",
    ]

    for capability in manifest.capabilities {
      let names = FacadeCapabilityNames(capabilityID: capability.id)
      lines.append("")
      lines.append("    public var \(names.propertyName): \(names.typeName) {")
      lines.append("        \(names.typeName)(openAPI: openAPI)")
      lines.append("    }")
    }

    lines.append("}")

    for capability in manifest.capabilities {
      let names = FacadeCapabilityNames(capabilityID: capability.id)
      lines.append("")
      lines.append("public struct \(names.typeName): Sendable {")
      lines.append("    public let openAPI: any APIProtocol")
      lines.append("")
      lines.append("    public init(openAPI: any APIProtocol) {")
      lines.append("        self.openAPI = openAPI")
      lines.append("    }")

      for operationID in capability.operations {
        let shape = operationShapes[operationID]!
        lines.append("")
        lines.append(contentsOf: renderMethod(for: shape))
      }

      lines.append("}")
    }

    lines.append("")
    return lines.joined(separator: "\n")
  }

  private func loadOperationShapes(from url: URL) throws -> [String: FacadeOperationShape] {
    let data = try Data(contentsOf: url)
    let document = try JSONDecoder().decode(FacadeOpenAPIDocument.self, from: data)
    var shapes: [String: FacadeOperationShape] = [:]

    for (_, pathItem) in document.paths {
      let pathParameters = pathItem.parameters ?? []

      for operation in pathItem.operations() {
        guard let operationID = operation.operationID else {
          continue
        }

        let parameters = pathParameters + (operation.parameters ?? [])
        let pathParameterNames =
          parameters
          .filter { $0.location == "path" }
          .map(\.name)
        let queryParameters = parameters.filter { $0.location == "query" }
        let enumName = pascalCase(operationID)

        shapes[operationID] = FacadeOperationShape(
          operationID: operationID,
          enumName: enumName,
          generatedMethodName: lowerFirst(enumName),
          facadeMethodName: facadeMethodName(for: operationID),
          pathParameterNames: pathParameterNames,
          hasQuery: !queryParameters.isEmpty,
          requiresQuery: queryParameters.contains { $0.required == true },
          hasBody: operation.hasRequestBody,
          isDeprecated: operation.isDeprecated
        )
      }
    }

    return shapes
  }

  private func renderMethod(for shape: FacadeOperationShape) -> [String] {
    let operationType = "Operations.\(shape.enumName)"
    var parameters: [String] = []

    for name in shape.pathParameterNames {
      parameters.append("\(swiftIdentifier(name)): Swift.String")
    }

    if shape.hasQuery {
      let suffix = shape.requiresQuery ? "" : " = .init()"
      parameters.append("query: \(operationType).Input.Query\(suffix)")
    }

    parameters.append("headers: \(operationType).Input.Headers = .init()")

    if shape.hasBody {
      parameters.append("body: \(operationType).Input.Body")
    }

    var lines: [String] = []

    if shape.isDeprecated {
      lines.append("    @available(*, deprecated)")
    }

    lines.append("    public func \(shape.facadeMethodName)(")

    for (index, parameter) in parameters.enumerated() {
      let trailing = index == parameters.count - 1 ? "" : ","
      lines.append("        \(parameter)\(trailing)")
    }

    lines.append("    ) async throws -> \(operationType).Output {")
    lines.append("        try await openAPI.\(shape.generatedMethodName)(.init(")

    let inputArguments = inputArguments(for: shape)
    for (index, argument) in inputArguments.enumerated() {
      let trailing = index == inputArguments.count - 1 ? "" : ","
      lines.append("            \(argument)\(trailing)")
    }

    lines.append("        ))")
    lines.append("    }")
    return lines
  }

  private func inputArguments(for shape: FacadeOperationShape) -> [String] {
    var arguments: [String] = []

    if !shape.pathParameterNames.isEmpty {
      let values = shape.pathParameterNames
        .map { "\($0): \(swiftIdentifier($0))" }
        .joined(separator: ", ")
      arguments.append("path: .init(\(values))")
    }

    if shape.hasQuery {
      arguments.append("query: query")
    }

    arguments.append("headers: headers")

    if shape.hasBody {
      arguments.append("body: body")
    }

    return arguments
  }

  private func facadeMethodName(for operationID: String) -> String {
    let parts = operationID.split(separator: "_", maxSplits: 1).map(String.init)
    guard parts.count == 2 else {
      return lowerFirst(pascalCase(operationID))
    }

    let resource = parts[0]
    let action = parts[1]
    let pluralResource = pascalCase(resource)
    let singularResource = pascalCase(singularize(resource))

    if action.hasSuffix("_getToManyRelated") {
      let relatedResource = String(action.dropLast("_getToManyRelated".count))
      return "list\(pascalCase(relatedResource))For\(singularResource)"
    }

    if action.hasSuffix("_getToOneRelated") {
      let relatedResource = String(action.dropLast("_getToOneRelated".count))
      return "get\(pascalCase(singularize(relatedResource)))For\(singularResource)"
    }

    switch action {
    case "getCollection":
      return "list\(pluralResource)"
    case "getInstance":
      return "get\(singularResource)"
    case "createInstance":
      return "create\(singularResource)"
    case "updateInstance":
      return "update\(singularResource)"
    case "deleteInstance":
      return "delete\(singularResource)"
    default:
      return lowerFirst(pascalCase(operationID))
    }
  }

  private func singularize(_ value: String) -> String {
    if value.hasSuffix("ies") {
      return String(value.dropLast(3)) + "y"
    }

    if value.hasSuffix("s"), value.count > 1 {
      return String(value.dropLast())
    }

    return value
  }

  private func pascalCase(_ value: String) -> String {
    value
      .split { !$0.isLetter && !$0.isNumber }
      .map { upperFirst(String($0)) }
      .joined()
  }

  private func swiftIdentifier(_ value: String) -> String {
    let identifier = lowerFirst(pascalCase(value))
    switch identifier {
    case "associatedtype", "class", "deinit", "enum", "extension", "func",
      "import", "init", "inout", "internal", "let", "operator", "private",
      "protocol", "public", "static", "struct", "subscript", "typealias",
      "var", "break", "case", "continue", "default", "defer", "do", "else",
      "fallthrough", "for", "guard", "if", "in", "repeat", "return", "switch",
      "where", "while":
      return "`\(identifier)`"
    default:
      return identifier
    }
  }

  private func upperFirst(_ value: String) -> String {
    guard let first = value.first else {
      return value
    }
    return first.uppercased() + value.dropFirst()
  }

  private func lowerFirst(_ value: String) -> String {
    guard let first = value.first else {
      return value
    }
    return first.lowercased() + value.dropFirst()
  }
}

private struct FacadeCapabilityNames {
  var propertyName: String
  var typeName: String

  init(capabilityID: String) {
    switch capabilityID {
    case "testflight":
      propertyName = "testFlight"
      typeName = "AppStoreConnectTestFlightClient"
    default:
      let typeStem =
        capabilityID
        .split(separator: "-")
        .map { String($0.prefix(1)).uppercased() + $0.dropFirst() }
        .joined()
      propertyName = typeStem.prefix(1).lowercased() + typeStem.dropFirst()
      typeName = "AppStoreConnect\(typeStem)Client"
    }
  }
}

private struct FacadeOperationShape: Sendable {
  var operationID: String
  var enumName: String
  var generatedMethodName: String
  var facadeMethodName: String
  var pathParameterNames: [String]
  var hasQuery: Bool
  var requiresQuery: Bool
  var hasBody: Bool
  var isDeprecated: Bool
}

private struct FacadeOpenAPIDocument: Decodable {
  var paths: [String: FacadePathItem]
}

private struct FacadePathItem: Decodable {
  var parameters: [FacadeParameter]?
  var get: FacadeOperation?
  var put: FacadeOperation?
  var post: FacadeOperation?
  var delete: FacadeOperation?
  var options: FacadeOperation?
  var head: FacadeOperation?
  var patch: FacadeOperation?
  var trace: FacadeOperation?

  func operations() -> [FacadeOperation] {
    [get, put, post, delete, options, head, patch, trace].compactMap { $0 }
  }
}

private struct FacadeOperation: Decodable {
  var operationID: String?
  var parameters: [FacadeParameter]?
  var hasRequestBody: Bool
  var isDeprecated: Bool

  enum CodingKeys: String, CodingKey {
    case operationID = "operationId"
    case parameters
    case requestBody
    case deprecated
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    operationID = try container.decodeIfPresent(String.self, forKey: .operationID)
    parameters = try container.decodeIfPresent([FacadeParameter].self, forKey: .parameters)
    hasRequestBody = container.contains(.requestBody)
    isDeprecated = try container.decodeIfPresent(Bool.self, forKey: .deprecated) ?? false
  }
}

private struct FacadeParameter: Decodable {
  var name: String
  var location: String
  var required: Bool

  enum CodingKeys: String, CodingKey {
    case name
    case location = "in"
    case required
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    name = try container.decodeIfPresent(String.self, forKey: .name) ?? ""
    location = try container.decodeIfPresent(String.self, forKey: .location) ?? ""
    required = try container.decodeIfPresent(Bool.self, forKey: .required) ?? false
  }
}
