// SPDX-License-Identifier: Apache-2.0 WITH Swift-exception
// Copyright (c) 2026 Xudong Xu

import AppStoreConnectCore
import Foundation
import OpenAPIURLSession

public enum AppStoreConnectSelectedOpenAPI: Sendable {
  public static let schemaVersion = "4.3"
  public static let capabilityIDs: [String] = [
    "apps",
    "builds",
    "testflight",
    "media-assets",
    "reports",
    "users",
    "certificates-profiles",
  ]
  public static let pathCount = 86
  public static let schemaCount = 255
  public static let operationIDs: [String] = [
    "appInfoLocalizations_createInstance",
    "appInfoLocalizations_deleteInstance",
    "appInfoLocalizations_getInstance",
    "appInfoLocalizations_updateInstance",
    "appInfos_getInstance",
    "appInfos_updateInstance",
    "appStoreReviewAttachments_createInstance",
    "appStoreReviewAttachments_deleteInstance",
    "appStoreReviewAttachments_getInstance",
    "appStoreReviewAttachments_updateInstance",
    "appStoreReviewDetails_createInstance",
    "appStoreReviewDetails_getInstance",
    "appStoreReviewDetails_updateInstance",
    "appStoreVersionLocalizations_createInstance",
    "appStoreVersionLocalizations_deleteInstance",
    "appStoreVersionLocalizations_getInstance",
    "appStoreVersionLocalizations_updateInstance",
    "appStoreVersionPhasedReleases_createInstance",
    "appStoreVersionPhasedReleases_deleteInstance",
    "appStoreVersionPhasedReleases_updateInstance",
    "appStoreVersionReleaseRequests_createInstance",
    "appStoreVersionSubmissions_deleteInstance",
    "appStoreVersions_createInstance",
    "appStoreVersions_deleteInstance",
    "appStoreVersions_getInstance",
    "appStoreVersions_updateInstance",
    "apps_appStoreVersions_getToManyRelated",
    "apps_getCollection",
    "apps_getInstance",
    "apps_updateInstance",
    "reviewSubmissionItems_createInstance",
    "reviewSubmissionItems_deleteInstance",
    "reviewSubmissionItems_updateInstance",
    "reviewSubmissions_createInstance",
    "reviewSubmissions_getCollection",
    "reviewSubmissions_getInstance",
    "reviewSubmissions_updateInstance",
    "buildBetaDetails_getCollection",
    "buildBetaDetails_getInstance",
    "buildBetaDetails_updateInstance",
    "buildBetaNotifications_createInstance",
    "buildUploadFiles_createInstance",
    "buildUploadFiles_getInstance",
    "buildUploadFiles_updateInstance",
    "buildUploads_createInstance",
    "buildUploads_deleteInstance",
    "buildUploads_getInstance",
    "builds_getCollection",
    "builds_getInstance",
    "builds_updateInstance",
    "preReleaseVersions_getCollection",
    "preReleaseVersions_getInstance",
    "betaAppLocalizations_createInstance",
    "betaAppLocalizations_deleteInstance",
    "betaAppLocalizations_getCollection",
    "betaAppLocalizations_getInstance",
    "betaAppLocalizations_updateInstance",
    "betaAppReviewDetails_getCollection",
    "betaAppReviewDetails_getInstance",
    "betaAppReviewDetails_updateInstance",
    "betaAppReviewSubmissions_createInstance",
    "betaAppReviewSubmissions_getCollection",
    "betaAppReviewSubmissions_getInstance",
    "betaBuildLocalizations_createInstance",
    "betaBuildLocalizations_deleteInstance",
    "betaBuildLocalizations_getCollection",
    "betaBuildLocalizations_getInstance",
    "betaBuildLocalizations_updateInstance",
    "apps_betaTesterUsages_getMetrics",
    "apps_betaFeedbackCrashSubmissions_getToManyRelated",
    "apps_betaFeedbackScreenshotSubmissions_getToManyRelated",
    "betaCrashLogs_getInstance",
    "betaGroups_betaTesterUsages_getMetrics",
    "betaGroups_publicLinkUsages_getMetrics",
    "betaFeedbackCrashSubmissions_crashLog_getToOneRelated",
    "betaFeedbackCrashSubmissions_getInstance",
    "betaFeedbackScreenshotSubmissions_getInstance",
    "betaGroups_createInstance",
    "betaGroups_deleteInstance",
    "betaGroups_getCollection",
    "betaGroups_getInstance",
    "betaGroups_updateInstance",
    "betaLicenseAgreements_getCollection",
    "betaLicenseAgreements_getInstance",
    "betaLicenseAgreements_updateInstance",
    "betaTesterInvitations_createInstance",
    "betaTesters_betaTesterUsages_getMetrics",
    "betaTesters_createInstance",
    "betaTesters_deleteInstance",
    "betaTesters_getCollection",
    "betaTesters_getInstance",
    "builds_betaBuildUsages_getMetrics",
    "appPreviewSets_createInstance",
    "appPreviewSets_deleteInstance",
    "appPreviewSets_getInstance",
    "appPreviews_createInstance",
    "appPreviews_deleteInstance",
    "appPreviews_getInstance",
    "appPreviews_updateInstance",
    "appScreenshotSets_createInstance",
    "appScreenshotSets_deleteInstance",
    "appScreenshotSets_getInstance",
    "appScreenshots_createInstance",
    "appScreenshots_deleteInstance",
    "appScreenshots_getInstance",
    "appScreenshots_updateInstance",
    "analyticsReportInstances_getInstance",
    "analyticsReportRequests_createInstance",
    "analyticsReportRequests_deleteInstance",
    "analyticsReportRequests_getInstance",
    "analyticsReportSegments_getInstance",
    "analyticsReports_getInstance",
    "financeReports_getCollection",
    "salesReports_getCollection",
    "userInvitations_createInstance",
    "userInvitations_deleteInstance",
    "userInvitations_getCollection",
    "userInvitations_getInstance",
    "users_deleteInstance",
    "users_getCollection",
    "users_getInstance",
    "users_updateInstance",
    "bundleIds_createInstance",
    "bundleIds_deleteInstance",
    "bundleIds_getCollection",
    "bundleIds_getInstance",
    "bundleIds_updateInstance",
    "certificates_createInstance",
    "certificates_deleteInstance",
    "certificates_getCollection",
    "certificates_getInstance",
    "certificates_updateInstance",
    "devices_createInstance",
    "devices_getCollection",
    "devices_getInstance",
    "devices_updateInstance",
    "profiles_createInstance",
    "profiles_deleteInstance",
    "profiles_getCollection",
    "profiles_getInstance",
  ]
}

extension Client {
  public static func appStoreConnectURLSession(
    serverURL: URL = URL(string: "https://api.appstoreconnect.apple.com")!,
    retryPolicy: AppStoreConnectRetryPolicy = .never
  ) -> Client {
    Client(
      serverURL: serverURL,
      transport: URLSessionTransport(),
      middlewares: [
        AppStoreConnectOpenAPIErrorMiddleware(),
        AppStoreConnectOpenAPIRetryMiddleware(policy: retryPolicy),
      ]
    )
  }
}
